# Generated by Django 6.0.2 on 2026-02-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_place_tbl_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_place',
            old_name='district',
            new_name='District_id',
        ),
        migrations.RenameField(
            model_name='tbl_place',
            old_name='place_name',
            new_name='place',
        ),
    ]
