# Generated by Django 6.0.2 on 2026-02-14 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_rename_district_tbl_place_district_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_place',
            old_name='District_id',
            new_name='district',
        ),
    ]
