# Generated by Django 6.0.2 on 2026-02-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='district',
        ),
    ]
