# Generated by Django 6.0.2 on 2026-02-18 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_rename_district_id_tbl_place_district'),
        ('Guest', '0003_alter_tbl_user_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_civilengineering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civileng_name', models.CharField(max_length=30)),
                ('civileng_email', models.CharField(max_length=30)),
                ('civileng_contact', models.CharField(max_length=30)),
                ('civileng_address', models.CharField(max_length=30)),
                ('civileng_photo', models.FileField(max_length=30, upload_to='')),
                ('civileng_proof', models.FileField(max_length=30, upload_to='')),
                ('civileng_password', models.CharField(max_length=30)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
