# Generated by Django 6.0.2 on 2026-02-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_civilengineering'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_civilengineering',
            name='civileng_status',
            field=models.IntegerField(default=0),
        ),
    ]
