# Generated by Django 6.0.2 on 2026-03-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_civilengineering_civileng_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_civilengineering',
            name='civileng_photo',
            field=models.FileField(upload_to='Assets/CivilEngineer/'),
        ),
        migrations.AlterField(
            model_name='tbl_civilengineering',
            name='civileng_proof',
            field=models.FileField(upload_to='Assets/CivilEngineer/'),
        ),
    ]
