# Generated by Django 6.0.2 on 2026-02-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_reply',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_status',
            field=models.IntegerField(default=0),
        ),
    ]
