# Generated by Django 6.0.2 on 2026-03-03 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_alter_tbl_civilengineering_civileng_photo_and_more'),
        ('User', '0002_alter_tbl_complaint_complaint_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=30)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_plane_file', models.FileField(upload_to='Assests/Request/')),
                ('request_doc', models.FileField(upload_to='Assest/Request/')),
                ('request_status', models.IntegerField(default=0)),
                ('request_reply', models.CharField(max_length=30, null=True)),
                ('request_description', models.CharField(max_length=30)),
                ('civileng_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_civilengineering')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
