# Generated by Django 6.0.2 on 2026-03-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_tbl_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_request',
            name='request_id',
        ),
    ]
